apiVersion: apps/v1
kind: Deployment
metadata:
  name: servicea
  labels:
    app: servicea
spec:
  replicas: 2
  selector:
    matchLabels:
      app: servicea
  template:
    metadata:
      labels:
        app: servicea
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8081"
    spec:
      containers:
        - name: servicea
          image: victorf13/servicea:latest
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8081
              protocol: TCP
          resources:
            requests:
              cpu: "100m"
