apiVersion: v1
kind: Service
metadata:
  name: servicea
  labels:
    app: servicea
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/actuator/prometheus"
    prometheus.io/port: "8081"
spec:
  type: ClusterIP
  selector:
    app: servicea
  ports:
    - name: http
      port: 8080
      targetPort: 8080
      protocol: TCP
