apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/actuator/prometheus"
        prometheus.io/port: "8080"
    spec:
      containers:
        - name: demo
          image:  "${DOCKER_USER}/demo:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          env:
            - name: APP_IMAGE_TAG
              value: "${IMAGE_TAG}"      # envsubst/Actions 注入
          resources:
            requests:
              cpu: "100m"           # 自動擴容的必要條件，需配置