apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: demo-hpa
  namespace: default
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: demo          # 要自動擴縮的 Deployment 名稱
  minReplicas: 2        # Pod 最少數量
  maxReplicas: 10       # Pod 最多數量
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 80   # CPU 使用率至 80% 以便高負載時自動擴容
