apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: demo
spec:
  ingressClassName: nginx
  rules:
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: demo
                port:
                  number: 8080
          - path: /servicea/
            pathType: Prefix
            backend:
              service:
                name: servicea
                port:
                  number: 8080
