spring:
  application:
    name: account-ledger-service
  datasource:
    url: jdbc:mysql://localhost:3306/ledger
    username: ledger
    password: ledger
    driver-class-name: com.mysql.cj.jdbc.Driver

logging:
  level:
    open.vincentf13.exchange.accountledger: INFO
