name: CI Build and Push

#
# 必須在 GitHub 專案設定 → Settings → Secrets and variables → Actions 中建立：
# 1. DOCKERHUB_USERNAME：可推送映像到 Docker Hub 的帳號。
# 2. DOCKERHUB_TOKEN：對應帳號的存取 token/密碼。
# 3. GH_PAT：至少擁有 repo 權限的 Personal Access Token，用來更新 GitOps 儲庫。
#

on:
  push:
    branches: ["**"]

# 集中管理各微服務目錄與對應的變更偵測
env:
  SERVICE_DIRS: |
    services/demo
    services/service-template
  SERVICE_GLOBS: |
    services/demo/**
    services/service-template/**

jobs:
  detect-changes:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.build-matrix.outputs.matrix }}
      has_changes: ${{ steps.build-matrix.outputs.has_changes }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      # Identify which microservices changed so downstream jobs can target only what is needed.
      - name: Detect changed microservices
        id: changed
        uses: tj-actions/changed-files@v45
        with:
          files: ${{ env.SERVICE_GLOBS }}
      - name: Log changed files
        if: steps.changed.outputs.all_changed_files != ''
        run: |
          echo "::group::Changed files"
          echo "${{ steps.changed.outputs.all_changed_files }}" | tr ' ' '\n'
          echo "::endgroup::"
      # Convert the changed file list into a build matrix consumable by later jobs.
      - name: Build service matrix
        id: build-matrix
        run: |
          set -euo pipefail
          echo "Building matrix from detected changes..."
          readarray -t services <<< "${SERVICE_DIRS}"
          declare -A seen=()
          matrix_entries=()
          while IFS= read -r file; do
            for svc in "${services[@]}"; do
              prefix="$svc/"
              if [[ $file == ${prefix}* && -z ${seen[$svc]:-} ]]; then
                seen[$svc]=1
                name=$(basename "$svc")
                slug=$(echo "$name" | tr '[:upper:]' '[:lower:]')
                matrix_entries+=("{\"service\":\"$svc\",\"name\":\"$name\",\"image_slug\":\"$slug\"}")
              fi
            done
          done < <(printf "%s\n%s\n" "${{ steps.changed.outputs.modified_files }}" "${{ steps.changed.outputs.added_files }}" | tr ' ' '\n' | sort -u)
          if [ ${#matrix_entries[@]} -eq 0 ]; then
            echo "has_changes=false" >> "$GITHUB_OUTPUT"
            echo 'matrix={"include":[]}' >> "$GITHUB_OUTPUT"
            echo "::notice::No microservice changes detected; downstream jobs will be skipped."
          else
            echo "has_changes=true" >> "$GITHUB_OUTPUT"
            joined_entries=$(IFS=, ; echo "${matrix_entries[*]}")
            matrix_json="{\"include\":[${joined_entries}]}"
            echo "matrix=${matrix_json}" >> "$GITHUB_OUTPUT"
            echo "Matrix definition: ${matrix_json}"
          fi

  build-and-push:
    needs: detect-changes
    if: needs.detect-changes.outputs.has_changes == 'true'
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJson(needs.detect-changes.outputs.matrix) }}
    env:
      TZ: Asia/Taipei
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Provision Java toolchain
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '23'
      # Build only the microservice under test; `-am` ensures dependencies are available.
      - name: Build service artifact
        env:
          IMAGE_TAG: ${{ github.sha }}
        run: |
          set -euo pipefail
          svc="${{ matrix.service }}"
          echo "::group::Building Maven artifacts for ${svc}"
          mvn -B -DskipTests -Duser.timezone=Asia/Taipei -Dimage.tag=${IMAGE_TAG} -pl "$svc" -am clean package
          echo "::endgroup::"
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3
      - name: Login to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      # Build/push the container image, tagging with short SHA plus latest.
      - name: Build and push image
        env:
          IMAGE_REPO: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          set -euo pipefail
          svc="${{ matrix.service }}"
          name="${{ matrix.name }}"
          slug="${{ matrix.image_slug }}"
          image="${IMAGE_REPO}/$slug"
          short_sha="${GITHUB_SHA::7}"
          echo "Building docker image ${image}:${short_sha} from ${svc}"
          echo "::group::Docker build logs"
          docker buildx build "$svc" \
            --file "$svc/Dockerfile" \
            --tag "$image:$short_sha" \
            --tag "$image:latest" \
            --push
          echo "::endgroup::"
      - name: Checkout GitOps repo
        if: github.event_name == 'push'
        uses: actions/checkout@v4
        with:
          repository: ${{ github.repository_owner }}/GitOps
          token: ${{ secrets.GH_PAT }}
          path: gitops
      - name: Update image tag in manifests
        if: github.event_name == 'push'
        id: manifest
        working-directory: gitops
        env:
          IMAGE_REPO: ${{ secrets.DOCKERHUB_USERNAME }}
          SERVICE_NAME: ${{ matrix.name }}
          IMAGE_SLUG: ${{ matrix.image_slug }}
        run: |
          set -eo pipefail
          short_sha="${GITHUB_SHA::7}"
          image="${IMAGE_REPO}/${IMAGE_SLUG}:$short_sha"
          deployment_path="k8s/${SERVICE_NAME}/deployment.yaml"
          if [ ! -f "$deployment_path" ]; then
            echo "skip=true" >> "$GITHUB_OUTPUT"
            echo "Missing deployment file for ${SERVICE_NAME}, nothing to update."
            exit 0
          fi
          echo "Updating ${deployment_path} to image ${image}"
          sed -i "s|image: .*${IMAGE_SLUG}:.*|image: ${image}|" "$deployment_path"
          echo "deployment_path=$deployment_path" >> "$GITHUB_OUTPUT"
          echo "skip=false" >> "$GITHUB_OUTPUT"
      - name: Commit and push manifest changes
        if: github.event_name == 'push' && steps.manifest.outputs.skip == 'false'
        uses: EndBug/add-and-commit@v9
        with:
          cwd: gitops
          add: ${{ steps.manifest.outputs.deployment_path }}
          message: "Update ${{ matrix.name }} image to ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_slug }}:${{ github.sha }}"
          push: true
          github_token: ${{ secrets.GH_PAT }}
