name: CI Build and Push

on:
  push:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and Push
        run: |
          IMAGE=victorf13/demo:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE
      - name: Update Manifests Repo
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update image to $IMAGE"
          add: "k8s/deployment.yaml"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}