name: CI Build and Push

on:
  push:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'
      - run: mvn -B -DskipTests package
      - name: Build and Push
        run: |
          IMAGE=victorf13/demo:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE
      - name: Checkout GitOps repo
        uses: actions/checkout@v3
        with:
          repository: Lilin-Li/GitOps
          token: ${{ secrets.GITHUB_TOKEN }}
          path: gitops
      - name: Update image tag in manifests
        run: |
          sed -i "s|image: victorf13/demo:.*|image: victorf13/demo:${{ github.sha }}|" k8s/deployment.yaml
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          message: "Update image to victorf13/demo:${{ github.sha }}"
          add: "gitops/k8s/deployment.yaml"
          push: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}