name: CI Build and Push

on:
  push:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '24'
      - run: mvn -B -DskipTests package
      - name: Build and Push
        run: |
          IMAGE=victorf13/demo:${{ github.sha }}
          docker build -t $IMAGE .
          docker push $IMAGE
      - name: Checkout GitOps repo
        uses: actions/checkout@v3
        with:
          repository: Lilin-Li/GitOps
          token: ${{ secrets.GH_PAT }}
          path: gitops
      - name: Update image tag in manifests
        working-directory: gitops
        run: |
          set -x                                                                                                                                                                                                                                                                                                                                  
          ls                                                                                                                                                                                                                                                                                                                                      
          test -f k8s/deployment.yaml                                                                                                                                                                                                                                                                                                             
          sed -i 's|image: victorf13/demo:.*|image: victorf13/demo:${{ github.sha }}|' k8s/deployment.yaml                                                                                                                                                                                                                                        
          grep -n 'image:' k8s/deployment.yaml || true                                                                                                                                                                                                                                                                                            
          git status --short || true 
      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          cwd: gitops
          add: k8s/deployment.yaml
          message: "Update image to victorf13/demo:${{ github.sha }}"
          push: true
          github_token: ${{ secrets.GH_PAT }}   # 關鍵：用 PAT 作為 input